/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import ModeloBeans.verificarLogin;
import ModeloConection.ConexaoBD;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author samsung
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    
    
    public TelaPrincipal() {
        initComponents();
      
         verificarLogin d = new verificarLogin();
         if ("GERENTE".equals(d.getFuncao())){
             CadastrarFuncionario.setEnabled(true);
         }else{
             CadastrarFuncionario.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        telainicial = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        TrocarDeConta = new javax.swing.JRadioButtonMenuItem();
        Inicio = new javax.swing.JMenu();
        CadastrarCliente = new javax.swing.JRadioButtonMenuItem();
        CadastrarFuncionario = new javax.swing.JMenuItem();
        cadastrarLivro = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CadastrarFuncionarios = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Emprestimo = new javax.swing.JRadioButtonMenuItem();
        Multa = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        Sair = new javax.swing.JMenu();
        sair = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telainicial.setFont(new java.awt.Font("Agency FB", 0, 13)); // NOI18N
        telainicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_Small.png"))); // NOI18N
        telainicial.setToolTipText("");

        jMenu2.setText("Usuario");

        TrocarDeConta.setSelected(true);
        TrocarDeConta.setText("Trocar De Conta");
        TrocarDeConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrocarDeContaActionPerformed(evt);
            }
        });
        jMenu2.add(TrocarDeConta);

        jMenuBar1.add(jMenu2);

        Inicio.setText("Cadastrar");

        CadastrarCliente.setSelected(true);
        CadastrarCliente.setText("Cadastrar Cliente");
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });
        Inicio.add(CadastrarCliente);

        CadastrarFuncionario.setText("Cadastrar Funcionario");
        CadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFuncionarioActionPerformed(evt);
            }
        });
        Inicio.add(CadastrarFuncionario);

        cadastrarLivro.setSelected(true);
        cadastrarLivro.setText("Cadastrar Livro");
        cadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLivroActionPerformed(evt);
            }
        });
        Inicio.add(cadastrarLivro);

        jMenu3.setText("Cadastrar Usuários");

        CadastrarFuncionarios.setSelected(true);
        CadastrarFuncionarios.setText("Cadastrar Funcionários");
        CadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(CadastrarFuncionarios);

        Inicio.add(jMenu3);

        jMenuBar1.add(Inicio);

        jMenu1.setText("Livros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Emprestimo.setSelected(true);
        Emprestimo.setText("Empréstimo");
        Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmprestimoActionPerformed(evt);
            }
        });
        jMenu1.add(Emprestimo);

        Multa.setSelected(true);
        Multa.setText("Multa");
        Multa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultaActionPerformed(evt);
            }
        });
        jMenu1.add(Multa);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Relatório");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Listar Clientes");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Listar Funcionarios");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Listar Livros");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Listar Emprestimos");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem4);

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Listar Multas");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem5);

        jMenuBar1.add(jMenu4);

        Sair.setText("Sair");

        sair.setSelected(true);
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        Sair.add(sair);

        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telainicial, javax.swing.GroupLayout.DEFAULT_SIZE, 1564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(telainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        // TODO add your handling code here:
        new CadastroCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void CadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        new CadastrarFuncionario().setVisible(true);
        dispose();
    }//GEN-LAST:event_CadastrarFuncionarioActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void TrocarDeContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrocarDeContaActionPerformed
        new TelaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_TrocarDeContaActionPerformed

    private void cadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLivroActionPerformed
       new CadastroLivro().setVisible(true);
       dispose();
    }//GEN-LAST:event_cadastrarLivroActionPerformed

    private void CadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFuncionariosActionPerformed
       new CadastrarUsuariosFuncionario().setVisible(true);
        dispose();
    }//GEN-LAST:event_CadastrarFuncionariosActionPerformed

    private void EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmprestimoActionPerformed
        new JFEmprestimo(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_EmprestimoActionPerformed

    private void MultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultaActionPerformed
        
        new JFMulta().setVisible(true);
        dispose();
    }//GEN-LAST:event_MultaActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        //FUNCIONARIOS
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "D:\\Usuários\\MARCOS RICHARD\\Downloads\\TrabalhoPoo\\POO3\\src\\MyReports\\Lista_Funcionarios.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);
        
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        //CLIENTES
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "D:\\Usuários\\MARCOS RICHARD\\Downloads\\TrabalhoPoo\\POO3\\src\\MyReports\\Lista_Clientes.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);
        
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        // TODO add your handling code here:
        //EMPRESTIMOS
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "D:\\Usuários\\MARCOS RICHARD\\Downloads\\TrabalhoPoo\\POO3\\src\\MyReports\\Lista_Empres.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);
        
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        //LIVROS
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "D:\\Usuários\\MARCOS RICHARD\\Downloads\\TrabalhoPoo\\POO3\\src\\MyReports\\Lista_Livros.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);
        
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        // TODO add your handling code here:
        //MULTAS
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "D:\\Usuários\\MARCOS RICHARD\\Downloads\\TrabalhoPoo\\POO3\\src\\MyReports\\Lista_Multas.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
               // telainicial.add(telaLogin);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem CadastrarCliente;
    private javax.swing.JMenuItem CadastrarFuncionario;
    private javax.swing.JRadioButtonMenuItem CadastrarFuncionarios;
    private javax.swing.JRadioButtonMenuItem Emprestimo;
    private javax.swing.JMenu Inicio;
    private javax.swing.JRadioButtonMenuItem Multa;
    private javax.swing.JMenu Sair;
    private javax.swing.JRadioButtonMenuItem TrocarDeConta;
    private javax.swing.JRadioButtonMenuItem cadastrarLivro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButtonMenuItem sair;
    private javax.swing.JLabel telainicial;
    // End of variables declaration//GEN-END:variables
}
